### ISSUE TITLE
Hover-Farbe für das Theme-Authentic anpassen -  Authentic 1.1

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components-theme#26]
Für das neue Layout muss die Hoverfarbe überarbeitet werden.
Z,B. bei der Table oder dem Accordion ist der Kontrast zu den neuen Themefarben zu gering.

![image](https://user-images.githubusercontent.com/49644099/175273076-68ad4bbd-cc11-4975-a37c-5b61c57c01e3.png)

**Comment by patrowe** [comment]
Im Rahmen einer ersten Iteration des neuen Themes, wurde das Verhalten bei hover/focus/seleceted grundlegend überarbeitet.
Weiterhin wurde folgende Styling-Issues mit umgesetzt Issue#239 lux-stepper-large-icon, Anzeige und Platzierung des Icons über das Css. Wegen des Issues#254, musste hierfür die Einbindungen der SVG-Datei überarbeite werden.

**Comment by patrowe** [comment]
Wegen des Issues#254 (https://github.com/IHK-GfI/lux-components/issues/254) werden SVG-Dateien nun direkt im css-Code bereitgestellt. Daher sind folgende Dateien erneut zu testen.

für das Theme-Authentic:
- lux-accarrdion (Pfeil im Panel-Header muss vorhanden sein)
- lux-select-ac (Pfeil im Input, im geöffneten Panel bei Single-Select, Checkmark hinter einem ausgewähltem Eintrag müssen vorhanden sein)
- lux-chips-ac (Pfeil im Input muss vorhanden sein)
- lux-header-ac (im geöffneten User-Menü muss ein "Checkmark" hinter dem Eintrag Theme-Authentic vorhanden sein)

für alle Themes:
-lux-stepper-large (nach Bearbeitung eines Steps erscheint ein "Checkmark" hinter dem Eintrag in der "Stepliste", vgl. https://github.com/IHK-GfI/lux-components/issues/239)

**Comment by thodic77** [comment]
@DSeifer: Bitte testen

**Comment by DSeifer** [comment]
Unter Windows 10 Enterprise 22H2 (19045.2486) und MacOS 13.2 mit den jeweils aktuellen Browserversionen getestet:

- lux-accordion (Pfeil im Panel-Header ist vorhanden)
- lux-select-ac (Pfeil im Input, im geöffneten Panel bei Single-Select, Checkmark hinter einem ausgewähltem Eintrag ist vorhanden)
- lux-chips-ac (Pfeil im Input ist vorhanden)
- lux-header-ac (im geöffneten User-Menü ist ein "Checkmark" hinter dem Eintrag Theme-Authentic vorhanden)
- für alle Themes:
- -lux-stepper-large (nach Bearbeitung eines Steps erscheint ein "Checkmark" hinter dem Eintrag in der "Stepliste")

MacOS: Safari, Chrome, Firefox -> OK
Windows: Edge, Firefox, Chrome, Opera -> OK
