### ISSUE TITLE
Umstellung auf das neue Modulsystem von Sass

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components-theme#30]
Im Jahr 2019 hat [Sass](https://sass-lang.com/) ein neues [Modulsystem](https://sass-lang.com/documentation/at-rules/use) vorgestellt. Anstatt [@import](https://sass-lang.com/documentation/at-rules/import) zu verwenden, nutzt man [@use](https://sass-lang.com/documentation/at-rules/use). 

Angular hat bereits auf das neue Modulsystem umgestellt. Im Rahmen dieses Issues soll das LUX-Theme ebenfalls auf das neue Modulsystem umgestellt werden.

**Comment by thodic77** [comment]
@patrowe: Bitte Code-Review durchführen und testen.

**Comment by patrowe** [comment]
Codereview erfolgreich durchgeführt. 
-Code kompiliert fehlerfrei,
-bei dem Test der Demo-Anwendungen, keine Auffälligkeiten in den beiden Themes entdeckt.
-Test durchgeführt unter Windows 10 mit den Browsern Edge und Chrome.
