### ISSUE TITLE
Icon-Buttons im Lux-App-Header-Ac sind nicht zentriert

### ISSUE THREAD

**Issue by patrowe** [IHK-GfI/lux-components-theme#32]
Die Icons in den Trigger-Buttons in der Top-Bar sind nicht zentriert. Dieses wird beim Hovern oder der Menüs sichtbar.

![image](https://user-images.githubusercontent.com/49644099/215481749-49edc5fb-2cec-465f-8466-2600cdcb9100.png)

**Comment by patrowe** [comment]
Der Fehler wurde behoben, die Icons sind nun zentriert in den Trigger-Buttons.
![image](https://user-images.githubusercontent.com/49644099/217201544-abbd21c6-bba8-4b4c-b3f5-36a7a99ae0e2.png)

Für den TEST:
Den Zweig https://github.com/IHK-GfI/lux-components/pull/272 auschecken und das Demo Programm starten.
Auf das Theme-Authentic wechseln und die Ansicht prüfen.
Durch Klicken auf die Triggerbuttons wechseln diese die Farbe und die Zentrierung der Icons kann gecheckt werden.
Alternativ kann mit TAB ein Button fokussiert werden.
![image](https://user-images.githubusercontent.com/49644099/217203025-1e9cb5d4-f4c7-487b-9441-e318772461a4.png)

**Comment by patrowe** [comment]
@DSeifer Bitte Testen!

**Comment by DSeifer** [comment]
Getestet unter Windows 10 Enterprise (20H2) und MacOS 13.2 mit folgenden Browsern in der jeweils aktuellen Version.
Windows 10: Edge, Firefox, Chrome, Opera -> OK
MacOS: Safari, Chrome, Firefox -> OK
