### ISSUE TITLE
Badge-Notification - Accent-Farbe noch ans Theme anpassen

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components-theme#7]
Die Badge-Notificationaccent-Farbe ist im Theme "green" noch nicht "das richtige grün"

![image](https://user-images.githubusercontent.com/32597554/136179836-01f941be-58d2-4784-87c3-cd3ec97dda07.png)

**Comment by patrowe** [comment]
@thodic77 : bitte testen

**Comment by thodic77** [comment]
Erfolgreich getestet.

![image](https://user-images.githubusercontent.com/32597554/136215189-0a4d25c2-c2c7-48b5-8941-38c08b87e16c.png)
