### ISSUE TITLE
Alte Material-Abhängigkeit 16.2.14 durch ^18.0.0 ersetzen

### ISSUE THREAD

**Issue by thodic77** [IHK-GfI/lux-components-theme#94]
**Akzeptanzkriterien**

- In der Datei _package.json_ steht die Abhängigkeit _@angular/material_ auf _^18.0.0_

**Comment by thodic77** [comment]
Die Abhängigkeit wurde ausgetauscht.

**Test**

- Die Demoseiten testen. 
- Es gibt leichte Pixeländerungen in den Komponenten Toggle, Checkbox, Radio, Slider, Badge-Notification und Tabs.
- Prüfen, ob die Komponenten normal funktionieren.

**Comment by thodic77** [comment]
@DSeifer: Bitte testen.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 (22H2/19045.5011) und MacOS 15.1.

### Windows
**Authentic-Theme:** OK

**Green-Theme:** 
Toggle -> luxDense hat deutlich geringere Auswirkungen als im Authentic-Theme
Checkbox -> luxDense hat deutlich geringere Auswirkungen als im Authentic-Theme
Radio -> Bei luxOrientationVertical hängen die Radiobuttons zu dicht zusammen. luxDense hat deutlich geringere Auswirkungen als im Authentic-Theme


### MacOS
**Authentic-Theme:** OK

**Green-Theme:** 
Toggle -> luxDense hat deutlich geringere Auswirkungen als im Authentic-Theme
Radio -> Bei luxOrientationVertical hängen die Radiobuttons zu dicht zusammen. luxDense hat deutlich geringere Auswirkungen als im Authentic-Theme

**Comment by thodic77** [comment]
Die Fehler wurden behoben. 

@DSeifer: Bitte nachtesten.

**Comment by DSeifer** [comment]
Getestet unter Windows 10 (22H2/19045.5011) im Edge Browser und MacOS 15.1 in Safari.

### Windows
**OK**

### MacOS
**OK**
